name: WikiSearch
description: A wikipidea search application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  core:
    path: core

  shared:
    path: shared

  dependencies:
    path: dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/default_logo.png"
  adaptive_icon_background: #000000

flutter:

  uses-material-design: true

  assets:
    - assets/
